### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by ClaraChaouat**
Hi @sandrina-p, 

## Summary 
Here is the very first shot of the grocery app using svelte.
So far, I built a basic layout of the app using svelte in a local environement. 

## Learnings
- Svelt fundamentals,
- Using svelte in a local environment,

 ## Struggles
- I can't find any tutorial about svelte and firebase realtime database. What do you think would be the best option? Working on another framework or using firebase cloud firestore?

Thanks for your feedback :).

### CODE REVIEW

**Comment by sandrina-p** [comment]
Hi @ClaraChaouat , this MR does not contain anything. the code is already one the main branch, I think you messed up with the branches :)

Remember:
main: empty, no files
working-branch: the actual code

**Comment by ClaraChaouat** [comment]
Hi @sandrina-p , 

Is that better this way?

**Comment by remotecom** [comment]
@ClaraChaouat , what did you change?. If you go to "Files changed" tab, it's still the same: 3 files deleted, no new code.

**Comment by sandrina-p** [comment]
@ClaraChaouat , what did you change? Perhaphs you forgot to push...
If you go to "Files changed" tab, it's still the same: 3 files deleted, no new code added :)

**Pull request closed without merging**
